[package]
authors = ["Julio Merino <jmmv@google.com>"]
categories = ["filesystems"]
description = "A virtual file system for sandboxing"
homepage = "https://github.com/bazelbuild/sandboxfs"
keywords = ["bazel", "filesystem", "fuse", "sandboxing"]
license = "Apache-2.0"
name = "sandboxfs"
readme = "README.md"
repository = "https://github.com/bazelbuild/sandboxfs"
version = "0.1.0"

[badges]
travis-ci = { repository = "bazelbuild/sandboxfs", branch = "master" }

[dependencies]
env_logger = "0.5"
failure = "0.1"
getopts = "0.2"
log = "0.4"
time = "0.1"

[dependencies.fuse]
# TODO(https://github.com/zargony/rust-fuse/pull/111): Replace this with
# the upstream address (or a Crates release) once incorporated.
git = "https://github.com/jmmv/rust-fuse.git"
rev = "152d2ad2fa8831be33fa5e691cc59ce9c51ece7a"

[dependencies.nix]
# TODO(jmmv): Replace this with 0.12 once released.
git = "https://github.com/nix-rust/nix.git"
rev = "771a2fc793f3b1a1d85408578ff3b054f22b041b"

[dev-dependencies]
tempdir = "0.3"
